services:
  nextjs:
    build:
      context: ./UI
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    env_file:
      - ./UI/.env
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./UI/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/agronexis.com/fullchain2.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/archive/agronexis.com/privkey2.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - nextjs
    networks:
      - webnet
  
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=AgroNexis@2025
      - MYSQL_PASSWORD=agroNexis@2025
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser

  app:
    image: nextcloud:28
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /etc/letsencrypt/archive/cloud.agronexis.com/fullchain2.pem:/etc/nginx/certs/cloud/fullchain.pem:ro
      - /etc/letsencrypt/archive/cloud.agronexis.com/privkey2.pem:/etc/nginx/certs/cloud/privkey.pem:ro
    environment:
      - MYSQL_PASSWORD=agroNexis@2025
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_HOST=db

networks:
  webnet:

volumes:
  db:
  nextcloud:
