services:
  nextjs:
    build:
      context: ./UI
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    env_file:
      - ./UI/.env
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./UI/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/agronexis.com/fullchain2.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/archive/agronexis.com/privkey2.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - nextjs
      - app
      - backend
    networks:
      - webnet
  
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=AgroNexis@2025
      - MYSQL_PASSWORD=agroNexis@2025
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
    networks:
      - webnet

  app:
    image: nextcloud:28
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /etc/letsencrypt/archive/cloud.agronexis.com/fullchain1.pem:/etc/nginx/certs/cloud/fullchain.pem:ro
      - /etc/letsencrypt/archive/cloud.agronexis.com/privkey1.pem:/etc/nginx/certs/cloud/privkey.pem:ro
    environment:
      - MYSQL_PASSWORD=agroNexis@2025
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_HOST=db
    networks:
      - webnet

  backend:
    container_name: backend
    restart: always
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=69.62.85.84;Port=5432;Database=agronexisdb;Username=agronexis;Password=agronexis@123
    depends_on:
      - backend-db
    networks:
      - webnet

  backend-db:
    container_name: backend-db
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: agronexisdb
      POSTGRES_USER: agronexis
      POSTGRES_PASSWORD: agronexis@123
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  db:
  nextcloud:
  backend-db-data:
